Fix broken links in drafts loaded with "load more" #1054
writefreely/writefreely pull request #1103
Opened 2024-10-17 19:00 UTC by vtyeh

### Description
This PR fixes broken edit links for drafts when loaded via 'load more' by dynamically generating the edit links based on the `single_user` config value.

Previously, drafts loaded with 'load more' had broken links because the link generation didn't account for the single-user mode and the path /pad/ seems to be deprecated.

Original issue description: [Issue #1054](https://github.com/writefreely/writefreely/issues/1054).

### Changes Made
- In `posts.js`, I introduced a new argument of `singleUser` to the `createPostEl` method
- In `articles.tmpl`, I pass down the single_user boolean to the `createPostEl` method

### How to Test
To verify the edit links work correctly in both single-user and multi-user modes:

1. Ensure you have more than 10 drafts
2. Set `single_user` = `true` in config.ini
3. Restart the app
4. Go to Drafts and click "Load more..."
5. Click "Edit" on one of the loaded drafts:
    - In single-user mode, the link should look like `/d/POSTID/edit`
    - In multi-user mode, it should look like `/POSTID/edit`
6. Set `single_user` = `false` in config.ini
7. Restart the app and repeat steps 4-5

### Related Ticket
https://github.com/writefreely/writefreely/issues/1054

### Additional Notes
I tried to see if introducing the new argument would cause any issues when the method is called elsewhere. I found that the other usages are in `posts.js` under `delPost` method. I am not sure how to test the functionality under the comment "Fill in full page of posts" to see if it is adversely affected by the introduction of the new method argument.

I found another minor bug while testing this and will open a separate issue for it. A quick summary: When deleting drafts, it doesn't refill the 10 latest drafts, so you can delete all 10 until all that is left is the Load more... link. Once you click it, the remaining drafts populate.

---

- [x] I have signed the [CLA](https://todo.musing.studio/L1)

2024-10-19 16:05 UTC, thebaer commented
Thanks for fixing this! Everything looks good at first glance, but I'll test shortly.

Please feel free to open a new issue for filling in more posts as you delete posts. I believe I have a fix ready to go for that already.

2024-10-21 21:36 UTC, vtyeh commented
Thank you!

I opened the [new issue](https://github.com/writefreely/writefreely/issues/1123).

2024-10-22 18:29 UTC, thebaer requested changes
This works perfectly!

Just one additional bug I noticed that I think we should fix here: loaded post titles (L198 in posts.js) should also have the condition applied. Single-user instances should link to `/d/{id}` and multi-user instances should still link to `/{id}`.

2024-10-22 20:43 UTC, vtyeh commented
Nice catch! I pulled out the link into its own variable since we use it multiple times. Just pushed up the new change.

2024-10-22 21:16 UTC, thebaer commented
Ah! That title link should actually go directly to the post page (without the `/edit` suffix), while the edit link should still go to `/edit`. Sorry for the confusion!

2024-10-23 17:34 UTC, vtyeh commented
Ah, no worries! That makes a lot of sense. I've pushed up the new change.

2024-10-24 15:39 UTC, thebaer approved these changes
Perfect! This looks great. Thanks again for contributing!

2024-10-24 15:39 UTC, merged