Increased `posts.content` size for MySQL.
writefreely/writefreely pull request #1145
Opened 2024-11-21 02:26 UTC by blacklight

`TEXT` -> 64kB
`MEDIUMTEXT` -> 16MB

Closes: https://github.com/writefreely/writefreely/issues/987

---

- [x] I have signed the [CLA](https://todo.musing.studio/L1)

2024-12-09 13:26 UTC, blacklight commented
Any plans to review/merge this? There's now a conflict because the v16 migration file has already been taken. I can quickly fix it but only if there's a plan to actually merge it (otherwise it's going to be a catch-up-with-db-migrations game).

2024-12-10 17:59 UTC, thebaer commented
Yep, happy to resolve this -- and thanks for contributing a fix! I'm a little concerned this might allow people to stuff a bunch of data into posts and fill up the database quickly. But that's probably not a major issue we need to address right now. Please feel free to fix this, and we'll get this merged. I'll also review the code shortly.

2024-12-10 18:08 UTC, thebaer requested changes
Thanks again for addressing this! Besides fixing the merge conflict, just one note here, and then you'll also want to add the migration function call to `migrations/migrations.go` in order for this to run.

2024-12-10 18:08 UTC, thebaer commented on schema.sql
> +  `content` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
This change isn't needed -- `schema.sql` only represents the initial state of the database, and then all migrations are applied over it.

2025-02-13 17:49 UTC, blacklight commented on schema.sql
> +  `content` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
@thebaer sorry for the delayed response. I have addressed this and updated the PR accordingly.

2025-02-25 18:28 UTC, thebaer requested changes
Thanks for updating this -- still one unaddressed issue:

> you'll also want to add the migration function call to `migrations/migrations.go` in order for this to run.

Right now, this migration never actually runs.

2025-05-01 07:41 UTC, blacklight commented
Any plans to merge this at some point?

2025-07-13 10:40 UTC, blacklight commented
This has been waiting to merge for too long. I'll close it because I'm not keen to keep it up-to-date with new db schema changes being merged before it. Feel free to reopen it and merge it if interested.

2025-07-13 10:40 UTC, closed without merging