Protect drafts if they are part of a Private or Protected collection
writefreely/writefreely pull request #528
Opened 2022-01-12 04:57 UTC by isaacsu

- Draft posts remain publicly accessible even after they are moved to a Private or Protected collection. 
- This PR causes writefreely to return with a 404 when a non-owner tries to access a draft post that has been moved to a Private or Protected collection.

--- 

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

2022-12-26 19:02 UTC, thebaer requested changes
Thanks for working on this, and sorry it's taken so long to review. Looks like some of the logic needs to be tweaked just a bit.

2022-12-26 19:02 UTC, thebaer commented on posts.go
> +		protectDraft = true
I believe this can be removed? Seems to make every single draft post private, even when it doesn't belong to a private / protected collection.

2023-01-05 01:02 UTC, isaacsu commented
Hi @thebaer, I've moved on from writefreely for the time being, so I won't be pursuing this PR any further. Happy for you to take over and run with it if you're keen. Regardless, thank you for creating writefreely and sharing so generously it with the world 🙏.

2023-11-07 15:11 UTC, thebaer commented
Thanks again for starting this @isaacsu! Merging this now.

2023-11-07 15:12 UTC, thebaer approved these changes

2023-11-07 15:12 UTC, merged